from django.core.management.base import BaseCommand
from core.models import Imovel

class Command(BaseCommand):
    help = 'Seeds the database with Juiz de Fora properties'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding data...')
        
        # Bairros: São Mateus, Alto dos Passos, Benfica, Centro
        properties = [
            # --- São Mateus ---
            {
                "titulo": "Apartamento Confortável em São Mateus",
                "descricao": "Ótimo apartamento de frente, sol da manhã, próximo ao Independência Shopping.",
                "quartos": 2,
                "banheiros": 2,
                "garagem": 1,
                "area": 85.00,
                "cidade": "Juiz de Fora",
                "bairro": "São Mateus",
                "rua": "Rua Padre Café",
                "numero": "120",
                "preco_aluguel": 1800.00,
                "preco_iptu": 150.00,
                "preco_condominio": 350.00,
                "aceita_pets": True,
            },
            {
                "titulo": "Cobertura Duplex São Mateus",
                "descricao": "Cobertura incrível com vista panorâmica, área gourmet e jacuzzi.",
                "quartos": 3,
                "banheiros": 3,
                "garagem": 2,
                "area": 160.00,
                "cidade": "Juiz de Fora",
                "bairro": "São Mateus",
                "rua": "Rua Dr. Romualdo",
                "numero": "450",
                "preco_aluguel": 3200.00,
                "preco_iptu": 300.00,
                "preco_condominio": 600.00,
                "aceita_pets": True,
            },
            {
                "titulo": "Studio Moderno Perto da UFJF",
                "descricao": "Studio mobiliado, ideal para estudantes, todo reformado e moderno.",
                "quartos": 1,
                "banheiros": 1,
                "garagem": 0,
                "area": 40.00,
                "cidade": "Juiz de Fora",
                "bairro": "São Mateus",
                "rua": "Av. Presidente Itamar Franco",
                "numero": "2000",
                "preco_aluguel": 1100.00,
                "preco_iptu": 80.00,
                "preco_condominio": 250.00,
                "aceita_pets": False,
            },

            # --- Alto dos Passos ---
            {
                "titulo": "Casa Charmosa no Alto dos Passos",
                "descricao": "Casa antiga reformada, com quintal arborizado e muita privacidade.",
                "quartos": 3,
                "banheiros": 2,
                "garagem": 2,
                "area": 200.00,
                "cidade": "Juiz de Fora",
                "bairro": "Alto dos Passos",
                "rua": "Rua Severiano Sarmento",
                "numero": "88",
                "preco_aluguel": 2500.00,
                "preco_iptu": 220.00,
                "preco_condominio": 0.00,
                "aceita_pets": True,
            },
            {
                "titulo": "Apartamento Luxo Alto dos Passos",
                "descricao": "Apartamento de alto padrão, um por andar, acabamento em porcelanato.",
                "quartos": 4,
                "banheiros": 4,
                "garagem": 3,
                "area": 220.00,
                "cidade": "Juiz de Fora",
                "bairro": "Alto dos Passos",
                "rua": "Rua Dom Viçoso",
                "numero": "300",
                "preco_aluguel": 4500.00,
                "preco_iptu": 500.00,
                "preco_condominio": 1200.00,
                "aceita_pets": True,
            },
            {
                "titulo": "Loft Industrial",
                "descricao": "Loft com pegada industrial, pé direito duplo e mezanino.",
                "quartos": 1,
                "banheiros": 1,
                "garagem": 1,
                "area": 70.00,
                "cidade": "Juiz de Fora",
                "bairro": "Alto dos Passos",
                "rua": "Rua Morais e Castro",
                "numero": "55",
                "preco_aluguel": 1900.00,
                "preco_iptu": 120.00,
                "preco_condominio": 400.00,
                "aceita_pets": False,
            },

            # --- Benfica ---
            {
                "titulo": "Casa Geminada em Benfica",
                "descricao": "Casa nova, entrada independente, em rua tranquila de Benfica.",
                "quartos": 2,
                "banheiros": 1,
                "garagem": 1,
                "area": 75.00,
                "cidade": "Juiz de Fora",
                "bairro": "Benfica",
                "rua": "Rua Martins Barbosa",
                "numero": "600",
                "preco_aluguel": 900.00,
                "preco_iptu": 50.00,
                "preco_condominio": 0.00,
                "aceita_pets": True,
            },
            {
                "titulo": "Apartamento Próximo ao Centro Comercial",
                "descricao": "Apartamento arejado, 2º andar, perto de bancos e supermercados.",
                "quartos": 2,
                "banheiros": 1,
                "garagem": 1,
                "area": 65.00,
                "cidade": "Juiz de Fora",
                "bairro": "Benfica",
                "rua": "Rua Tomé de Souza",
                "numero": "150",
                "preco_aluguel": 850.00,
                "preco_iptu": 60.00,
                "preco_condominio": 150.00,
                "aceita_pets": True,
            },
            {
                "titulo": "Casa de Vila em Benfica",
                "descricao": "Casa aconchegante em vila fechada, segurança e tranquilidade.",
                "quartos": 2,
                "banheiros": 1,
                "garagem": 1,
                "area": 80.00,
                "cidade": "Juiz de Fora",
                "bairro": "Benfica",
                "rua": "Av. Juscelino Kubitschek",
                "numero": "7000",
                "preco_aluguel": 1200.00,
                "preco_iptu": 80.00,
                "preco_condominio": 50.00,
                "aceita_pets": True,
            },

            # --- Centro ---
            {
                "titulo": "Kitnet no Calçadão",
                "descricao": "No coração da cidade, perto de tudo. Portaria 24h.",
                "quartos": 1,
                "banheiros": 1,
                "garagem": 0,
                "area": 30.00,
                "cidade": "Juiz de Fora",
                "bairro": "Centro",
                "rua": "Rua Halfeld",
                "numero": "700",
                "preco_aluguel": 800.00,
                "preco_iptu": 70.00,
                "preco_condominio": 250.00,
                "aceita_pets": False,
            },
            {
                "titulo": "Apartamento 3 Quartos Centro",
                "descricao": "Apartamento clássico, cômodos grandes, dependência de empregada completa.",
                "quartos": 3,
                "banheiros": 2,
                "garagem": 1,
                "area": 140.00,
                "cidade": "Juiz de Fora",
                "bairro": "Centro",
                "rua": "Av. Rio Branco",
                "numero": "2300",
                "preco_aluguel": 2200.00,
                "preco_iptu": 250.00,
                "preco_condominio": 700.00,
                "aceita_pets": True,
            },
             {
                "titulo": "Apartamento Reformado Rio Branco",
                "descricao": "Apartamento andar alto, vista livre, todo reformado.",
                "quartos": 2,
                "banheiros": 2,
                "garagem": 1,
                "area": 90.00,
                "cidade": "Juiz de Fora",
                "bairro": "Centro",
                "rua": "Av. Rio Branco",
                "numero": "1800",
                "preco_aluguel": 1600.00,
                "preco_iptu": 180.00,
                "preco_condominio": 450.00,
                "aceita_pets": True,
            },
        ]
        
        Imovel.objects.all().delete()
        # Helper to assign images in round-robin
        images = ['casa1.jpg', 'casa2.jpg', 'casa3.jpg']
        
        for i, prop in enumerate(properties):
            prop['imagem'] = images[i % len(images)]
            Imovel.objects.create(**prop)
            
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(properties)} properties in Juiz de Fora'))
