# Generated by Django 6.0.2 on 2026-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('garagem', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('preco_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_iptu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_condominio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aceita_pets', models.BooleanField(default=False)),
            ],
        ),
    ]
